org 000h

; DATA SEGMENTI ISTENEN YERE ALDIM
MOV AX,0700H
MOV DS,AX
MOV AX,0
MOV SI,0000H

; PARITY BITLERI YERLESTIRILECEK ADRESI BX'E ATTIM
MOV BX,0300H
 
MOV WORD PTR [SI],0013H ; 1.SAYI --> [0700:0000] PARITY -->[0700:0300]
ADD SI,2
MOV WORD PTR [SI],3331H

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2

MOV WORD PTR [SI],0003H ; 2.SAYI --> [0700:0004] PARITY -->[0700:0301]
ADD SI,2
MOV WORD PTR [SI],3331H

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2

MOV WORD PTR [SI],1224H ; 3.SAYI --> [0700:0008] PARITY -->[0700:0302]
ADD SI,2
MOV WORD PTR [SI],9651H

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2

MOV WORD PTR [SI],3315H ; 4.SAYI --> [0700:000C] PARITY -->[0700:0303]
ADD SI,2
MOV WORD PTR [SI],06ABH

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2
                                  
MOV WORD PTR [SI],0DD12H ; 5.SAYI --> [0700:0010] PARITY -->[0700:0304]
ADD SI,2
MOV WORD PTR [SI],4F64H

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2

MOV WORD PTR [SI],1123H ; 6.SAYI --> [0700:0014] PARITY -->[0700:0305]
ADD SI,2
MOV WORD PTR [SI],0E129H

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2

MOV WORD PTR [SI],561EH ; 7.SAYI --> [0700:0018] PARITY -->[0700:0306]
ADD SI,2
MOV WORD PTR [SI],557CH

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2

MOV WORD PTR [SI],1212H ; 8.SAYI --> [0700:001C] PARITY -->[0700:0307]
ADD SI,2
MOV WORD PTR [SI],21EEH

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2

MOV WORD PTR [SI],4310H ; 9.SAYI --> [0700:0020] PARITY -->[0700:0308]
ADD SI,2
MOV WORD PTR [SI],0012H

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2

MOV WORD PTR [SI],0101H ; 10.SAYI --> [0700:0024] PARITY -->[0700:0309]
ADD SI,2
MOV WORD PTR [SI],9912H

CALL PARITY ;VERILEN SAYI ICIN PARITY HESAPLAMA ALTPROGRAMINI CAGIRDIM
ADD SI,2


MOV BX,0300H
MOV AX,0

; LED DISPLAYDE YAZDIRMAK ICIN SINIRSIZ DONGU (110 PORTUNA 1 YAZILIRSA ILK SAYIYI VERIR [0700:0300] ADRESI YANI)
PRINTLOOP:
    IN AL,110
    MOV SI,AX
    MOV AL, [BX+SI-1]
    OUT 199,AX
    JMP PRINTLOOP


HLT ; SON ISLEMDEN SONRA PROGRAMIN BITMESI ICIN


PARITY PROC
    MOV CX,0 ; ESKI ISLEMLERLE KARISMAMASI ICIN CX SIFIRLANDI, WORD WORD PARITY TUTMAKTAYDI
    MOV DX,0
    MOV DI,SI ; SI REGISTERINI BOZMAMAK ICIN DI'YA ATTIM
    SUB DI,2 ; EN BASINDAN BASLAMAK ICIN GERI ALDIM
    MOV AX, WORD PTR [DI] ; PARITYSI HESAPLANACAK DEGERI AX'E ATTIM
    
    XOR AL,0 ; AX ICINDEKI DEGER ICIN PARITY HESAPLA
    JPO ODD1 ; PARITY TEK ISE ODD1 ETIKETINE ATLA
    JPE EVEN1 ; PARITY CIFT ISE EVEN1 ETIKETINE ATLA
    
    FINISH:
      RET ; ALT PROGRAMI BITIRMESI ICIN  
    
    
ODD1:
    MOV CL,1 ; ILK BYTEIN PARITYSI 1 OLDUGU ICIN CL'DE BU DEGERI TUTTUM
    XOR AH,0 ; XOR ILE PARITY FLAGINI 0 VEYA 1 OLARAK DUZENLETMEYI SAGLADIM
    JPO ODD2 ; DIGER BYTEIN PARITYSI TEK ISE ODD2 ETIKETINE ATLA
    JPE EVEN2 ; DIGER BYTEIN PARITYSI CIFT ISE EVEN2 ETIKETINE ATLA

EVEN1:
    MOV CL,0 ; ILK BYTEIN PARITYSI 0 OLDUGU ICIN CL'DE BU DEGERI TUTTUM
    XOR AH,0 ; XOR ILE PARITY FLAGINI 0 VEYA 1 OLARAK DUZENLETMEYI SAGLADIM
    JPO ODD2 ; DIGER BYTEIN PARITYSI TEK ISE ODD2 ETIKETINE ATLA
    JPE EVEN2 ; DIGER BYTEIN PARITYSI CIFT ISE EVEN2 ETIKETINE ATLA    

ODD2:
    MOV CH,1 ; IKINCI BYTEIN PARITYSI 1 OLDUGUNDAN DOLAYI CL'DE DE ILK BYTEIN PARITYSI TUTULDUGUNDAN CH KISMINA BU DEGERI ATADIM
    MOV AX, WORD PTR [DI+2]
    XOR AL,0
    JPO ODD3
    JPE EVEN3 

EVEN2:
    MOV CH,0 ; IKINCI BYTEIN PARITYSI 0 OLDUGUNDAN DOLAYI CL'DE DE ILK BYTEIN PARITYSI TUTULDUGUNDAN CH KISMINA BU DEGERI ATADIM 
    MOV AX, WORD PTR [DI+2]
    XOR AL,0
    JPO ODD3
    JPE EVEN3
    
ODD3:
    MOV DL,1 ; UCUNCU BYTEIN PARITYSI 1 OLDUGUNDAN DOLAYI CX'DE DE ILK WORDUN PARITYSI TUTULDUGUNDAN DL KISMINA BU DEGERI ATADIM
    XOR AH,0
    JPO ODD4
    JPE EVEN4

EVEN3:
    MOV DL,0 ; UCUNCU BYTEIN PARITYSI 0 OLDUGUNDAN DOLAYI CX'DE DE ILK WORDUN PARITYSI TUTULDUGUNDAN DL KISMINA BU DEGERI ATADIM
    XOR AH,0
    JPO ODD4
    JPE EVEN4

ODD4:
    MOV DH,1 ; DORDUNCU BYTEIN PARITYSI 1 OLDUGUNDAN DOLAYI CX'DE ILK WORDUN PARITYSI, DL'DE DE UCUNCU BYTEIN PARITYSI TUTULDUGUNDAN DH KISMINA BU DEGERI ATADIM
    
    CMP CH,CL ; ILK WORDUN PARITYSINI HESAPLADIM
    JZ LOWWORD0
    JNZ LOWWORD1
    
EVEN4:
    MOV DH,0 ; DORDUNCU BYTEIN PARITYSI 0 OLDUGUNDAN DOLAYI CX'DE ILK WORDUN PARITYSI, DL'DE DE UCUNCU BYTEIN PARITYSI TUTULDUGUNDAN DH KISMINA BU DEGERI ATADIM
    
    CMP CH,CL ; ILK WORDUN PARITYSINI HESAPLADIM
    JZ LOWWORD0
    JNZ LOWWORD1

LOWWORD0:
    MOV CH,0 ; ILK WORDUN PARITYSI 0 ISE CH'I 0 YAPTIM
    
    CMP DH,DL ; IKINCI WORDUN PARITYSINI HESAPLADIM
    JZ HIGHWORD0
    JNZ HIGHWORD1

LOWWORD1:
    MOV CH,1 ; ILK WORDUN PARITYSI 1 ISE CH'I 1 YAPTIM
    
    CMP DH,DL ; IKINCI WORDUN PARITYSINI HESAPLADIM
    JZ HIGHWORD0
    JNZ HIGHWORD1    

HIGHWORD0:
    MOV DH,0 ; IKINCI WORDUN PARITYSI 0 ISE DH'I 0 YAPTIM
    
    CMP DH,CH ; SON SONUCU HESAPLATMA
    JZ PF0
    JNZ PF1
    
HIGHWORD1:
    MOV DH,1 ; IKINCI WORDUN PARITYSI 1 ISE DH'I 1 YAPTIM
    
    CMP DH,CH ; SON SONUCU HESAPLATMA
    JZ PF0
    JNZ PF1

PF0:
    MOV BYTE PTR [BX],0H ; BX'TEKI OFFSETE PARITY 0 OLDUGU ICIN 0 ATADIM
    INC BX ; SONRAKI SAYININ PARITYSININ YAZILACAGI YENI KONUMA GECTIM
    JMP FINISH

PF1:
    MOV BYTE PTR [BX],1H ; BX'TEKI OFFSETE PARITY 1 OLDUGU ICIN 1 ATADIM
    INC BX ; SONRAKI SAYININ PARITYSININ YAZILACAGI YENI KONUMA GECTIM
    JMP FINISH
      
PARITY ENDP
    